// Public Google Play snapshot. See docs/curated-showcase.md for ranking rules.
import type { StoreMetrics } from './catalog';

export const storeMetrics: Record<string, StoreMetrics> = {
  kride: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.kakaomobility.kride&hl=en&gl=US',
    storeName: 'k.ride - taxi, cab, korea trip',
    publisher: 'Kakao Mobility Corp.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 3309,
    downloadsLowerBound: 100000,
  },
  'google-crowdsource': {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.google.android.apps.village.boond&hl=en&gl=US',
    storeName: 'Crowdsource',
    publisher: 'Google LLC',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 16220,
    downloadsLowerBound: 1000000,
  },
  '9gag': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.ninegag.android.app&hl=en&gl=US',
    storeName: '9GAG: Funny GIF, Meme & Video',
    publisher: '9gag',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 1714703,
    downloadsLowerBound: 10000000,
  },
  agape: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.getdailyagape&hl=en&gl=US',
    storeName: 'Agapé: Feel Close When Apart',
    publisher: 'Agapé',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 9554,
    downloadsLowerBound: 500000,
  },
  bluesky: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=xyz.blueskyweb.app&hl=en&gl=US',
    storeName: 'Bluesky',
    publisher: 'Bluesky PBLLC',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 58051,
    downloadsLowerBound: 10000000,
  },
  bolt: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=ee.mtakso.client&hl=en&gl=US',
    storeName: 'Bolt: Request a Ride',
    publisher: 'Bolt Technology',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 10720884,
    downloadsLowerBound: 100000000,
  },
  bounce: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.usebounce&hl=en&gl=US',
    storeName: 'Bounce: Luggage Storage Nearby',
    publisher: 'Bounce, Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 13839,
    downloadsLowerBound: 1000000,
  },
  cameo: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.baronapp.cameo&hl=en&gl=US',
    storeName: 'Cameo - Personal celeb videos',
    publisher: 'Cameo - Personalized Shoutouts',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 20400,
    downloadsLowerBound: 1000000,
  },
  'dine-by-wix': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.wix.restaurants&hl=en&gl=US',
    storeName: 'Dine by Wix',
    publisher: 'Wix.com, INC.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 726,
    downloadsLowerBound: 100000,
  },
  cz: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=nl.cz.app&hl=en&gl=US',
    storeName: 'CZ',
    publisher: 'CZ Zorgverzekeringen',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 23294,
    downloadsLowerBound: 1000000,
  },
  'fit-by-wix': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.wix.fitness&hl=en&gl=US',
    storeName: 'Fit by Wix: Book, manage, pay ',
    publisher: 'Wix.com, INC.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 1764,
    downloadsLowerBound: 500000,
  },
  lingvano: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.lingvano.app&hl=en&gl=US',
    storeName: 'Lingvano: Sign Language - ASL',
    publisher: 'Lingvano',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 78085,
    downloadsLowerBound: 1000000,
  },
  monta: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.montaapp.monta&hl=en&gl=US',
    storeName: 'Monta Charge',
    publisher: 'Monta ApS',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 8043,
    downloadsLowerBound: 100000,
  },
  'mgm-resorts': {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.mgmresorts.mgmresorts&hl=en&gl=US',
    storeName: 'MGM Rewards',
    publisher: 'MGM Resorts International',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 31302,
    downloadsLowerBound: 1000000,
  },
  nubank: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.nu.production&hl=en&gl=US',
    storeName: 'Nu: Everyday mobile banking',
    publisher: 'Nu',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 5839401,
    downloadsLowerBound: 100000000,
  },
  'mta-traintime': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.mta.mobileapp&hl=en&gl=US',
    storeName: 'MTA TrainTime',
    publisher: 'MTA (Metropolitan Transportation Authority)',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 27710,
    downloadsLowerBound: 1000000,
  },
  romwe: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.romwe&hl=en&gl=US',
    storeName: 'ROMWE - Ultimate Cyber Mall',
    publisher: 'Roadget Business PTE. LTD.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 393701,
    downloadsLowerBound: 10000000,
  },
  reflection: {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=app.reflection.reflection&hl=en&gl=US',
    storeName: 'Reflection: AI Journal & Coach',
    publisher: 'Reflection.app',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 2335,
    downloadsLowerBound: 100000,
  },
  'so-vegan': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.wearesovegan.app&hl=en&gl=US',
    storeName: 'SO VEGAN: Healthy Recipes',
    publisher: 'SO VEGAN',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 350,
    downloadsLowerBound: 10000,
  },
  skandia: {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=se.skandiabanken.android.wallet&hl=en&gl=US',
    storeName: 'Skandia och Skandiabanken',
    publisher: 'Livförsäkringsbolaget Skandia, ömsesidigt',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 2301,
    downloadsLowerBound: 100000,
  },
  sozcu: {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=org.studionord.sozcu.gazete&hl=en&gl=US',
    storeName: 'Sözcü Gazetesi - Haberler',
    publisher: 'Estetik Yayıncılık',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 13918,
    downloadsLowerBound: 1000000,
  },
  stage: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=in.stage&hl=en&gl=US',
    storeName: 'STAGE Films, Web-Series, Shows',
    publisher: 'STAGE Technologies Private Limited',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 191462,
    downloadsLowerBound: 10000000,
  },
  superlist: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.superlist.superlist&hl=en&gl=US',
    storeName: 'Superlist: To-Do List & Notes',
    publisher: 'Superlist',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 1408,
    downloadsLowerBound: 100000,
  },
  'universal-parks': {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.universalstudios.orlandoresort&hl=en&gl=US',
    storeName: 'Universal Orlando Resort',
    publisher: 'NBCUniversal Media, LLC',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 9087,
    downloadsLowerBound: 5000000,
  },
  xianyu: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.taobao.idlefish&hl=en&gl=US',
    storeName: '闲鱼',
    publisher: 'Taobao',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 10754,
    downloadsLowerBound: 1000000,
  },
  toss: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=viva.republica.toss&hl=en&gl=US',
    storeName: 'Toss',
    publisher: 'Viva Republica',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 253512,
    downloadsLowerBound: 10000000,
  },
  'my-bmw': {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=de.bmw.connected.mobile20.na&hl=en&gl=US',
    storeName: 'My BMW',
    publisher: 'BMW',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 40809,
    downloadsLowerBound: 500000,
  },
  duolingo: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.duolingo&hl=en&gl=US',
    storeName: 'Duolingo: Language Lessons',
    publisher: 'Duolingo',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 49125919,
    downloadsLowerBound: 500000000,
  },
  facebook: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.facebook.katana&hl=en&gl=US',
    storeName: 'Facebook',
    publisher: 'Meta Platforms, Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 185553138,
    downloadsLowerBound: 10000000000,
  },
  notebooklm: {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.google.android.apps.labs.language.tailwind&hl=en&gl=US',
    storeName: 'Gemini Notebook',
    publisher: 'Google LLC',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 301025,
    downloadsLowerBound: 10000000,
  },
  'sony-headphones': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.sony.songpal.mdr&hl=en&gl=US',
    storeName: 'Sony | Sound Connect',
    publisher: 'Sony Corporation',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 407486,
    downloadsLowerBound: 10000000,
  },
  'booking-com': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.booking&hl=en&gl=US',
    storeName: 'Booking.com: Hotels & Travel',
    publisher: 'Booking.com Hotels & Vacation Rentals',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 6336893,
    downloadsLowerBound: 500000000,
  },
  'meta-ads-manager': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.facebook.adsmanager&hl=en&gl=US',
    storeName: 'Meta Ads Manager',
    publisher: 'Meta Platforms, Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 568761,
    downloadsLowerBound: 10000000,
  },
  'google-classroom': {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.google.android.apps.classroom&hl=en&gl=US',
    storeName: 'Google Classroom',
    publisher: 'Google LLC',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 2089518,
    downloadsLowerBound: 100000000,
  },
  philo: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.philo.philo.google&hl=en&gl=US',
    storeName: 'Philo: Shows, Movies, Live TV.',
    publisher: 'Philo, Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 38252,
    downloadsLowerBound: 5000000,
  },
  'meta-horizon': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.oculus.twilight&hl=en&gl=US',
    storeName: 'Meta Horizon',
    publisher: 'Meta Platforms Inc',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 147884,
    downloadsLowerBound: 10000000,
  },
  hm: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.hm.goe&hl=en&gl=US',
    storeName: 'H&M',
    publisher: 'H&M',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 1032165,
    downloadsLowerBound: 100000000,
  },
  'microsoft-office': {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.microsoft.office.officehubrow&hl=en&gl=US',
    storeName: 'Microsoft Copilot',
    publisher: 'Microsoft Corporation',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 9201352,
    downloadsLowerBound: 1000000000,
  },
  knowunity: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=de.knowunity.app&hl=en&gl=US',
    storeName: 'Knowunity: AI Study & Homework',
    publisher: 'Knowunity',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 127706,
    downloadsLowerBound: 10000000,
  },
  bitkey: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=world.bitkey.app&hl=en&gl=US',
    storeName: 'Bitkey - Bitcoin Wallet',
    publisher: 'Block, Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 146,
    downloadsLowerBound: 10000,
  },
  'microsoft-outlook': {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.microsoft.office.outlook&hl=en&gl=US',
    storeName: 'Microsoft Outlook',
    publisher: 'Microsoft Corporation',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 10629739,
    downloadsLowerBound: 1000000000,
  },
  sofi: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.sofi.mobile&hl=en&gl=US',
    storeName: 'SoFi: Bank, Invest & Crypto',
    publisher: 'Social Finance, LLC',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 53598,
    downloadsLowerBound: 5000000,
  },
  markaz: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.markaz.app&hl=en&gl=US',
    storeName: 'Markaz: Pakistan Shopping App',
    publisher: 'Markaz Technologies',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 40156,
    downloadsLowerBound: 5000000,
  },
  'microsoft-teams': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.microsoft.teams&hl=en&gl=US',
    storeName: 'Microsoft Teams',
    publisher: 'Microsoft Corporation',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 8746923,
    downloadsLowerBound: 500000000,
  },
  kqed: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=org.kqed.android&hl=en&gl=US',
    storeName: 'KQED: Bay Area Culture & News',
    publisher: 'KQED',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 829,
    downloadsLowerBound: 50000,
  },
  opensooq: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.opensooq.OpenSooq&hl=en&gl=US',
    storeName: 'السوق المفتوح - OpenSooq',
    publisher: 'OpenSooq FZ-LLC',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 617692,
    downloadsLowerBound: 50000000,
  },
  'amazon-shopping': {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.amazon.mShop.android.shopping&hl=en&gl=US',
    storeName: 'Amazon Shopping',
    publisher: 'Amazon Mobile LLC',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 4680347,
    downloadsLowerBound: 1000000000,
  },
  talabat: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.talabat&hl=en&gl=US',
    storeName: 'talabat: Food, grocery & more',
    publisher: 'Talabat',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 544128,
    downloadsLowerBound: 50000000,
  },
  'amazon-alexa': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.amazon.dee.app&hl=en&gl=US',
    storeName: 'Amazon Alexa',
    publisher: 'Amazon Mobile LLC',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 5696935,
    downloadsLowerBound: 100000000,
  },
  'zoho-tables': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.zoho.tables&hl=en&gl=US',
    storeName: 'Zoho Tables - Plan & Track',
    publisher: 'Zoho Corporation',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 160,
    downloadsLowerBound: 10000,
  },
  'amazon-photos': {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.amazon.clouddrive.photos&hl=en&gl=US',
    storeName: 'Amazon Photos: Photo & Video',
    publisher: 'Amazon Mobile LLC',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 1105727,
    downloadsLowerBound: 50000000,
  },
  karaca: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=net.btpro.client.karaca&hl=en&gl=US',
    storeName: 'Karaca: Ev & Yaşam Alışverişi',
    publisher: 'KARACA',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 113039,
    downloadsLowerBound: 10000000,
  },
  quizlet: {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.quizlet.quizletandroid&hl=en&gl=US',
    storeName: 'Quizlet: More than Flashcards',
    publisher: 'Quizlet Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 911133,
    downloadsLowerBound: 50000000,
  },
  shopify: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.shopify.mobile&hl=en&gl=US',
    storeName: 'Shopify: Sell online/in person',
    publisher: 'Shopify Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 71828,
    downloadsLowerBound: 10000000,
  },
  kikoff: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.kikoff&hl=en&gl=US',
    storeName: 'Kikoff - Build Credit Quickly',
    publisher: 'Kikoff Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 131276,
    downloadsLowerBound: 5000000,
  },
  memrise: {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.memrise.android.memrisecompanion&hl=en&gl=US',
    storeName: 'Memrise: Languages for life',
    publisher: 'Memrise',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 1571632,
    downloadsLowerBound: 50000000,
  },
  shop: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.shopify.arrive&hl=en&gl=US',
    storeName: 'Shop: Track, Pay, Discover',
    publisher: 'Shopify Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 718515,
    downloadsLowerBound: 50000000,
  },
  forbes: {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.forbes.forbesreader.android&hl=en&gl=US',
    storeName: 'Forbes',
    publisher: 'Forbes Mobile',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 46,
    downloadsLowerBound: 10000,
  },
  'shopify-inbox': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.shopify.ping&hl=en&gl=US',
    storeName: 'Shopify Inbox',
    publisher: 'Shopify Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 7921,
    downloadsLowerBound: 500000,
  },
  'shopify-pos': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.shopify.pos&hl=en&gl=US',
    storeName: 'Shopify Point of Sale (POS)',
    publisher: 'Shopify Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 3543,
    downloadsLowerBound: 1000000,
  },
  headspace: {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.getsomeheadspace.android&hl=en&gl=US',
    storeName: 'Headspace: Sleep & Meditation',
    publisher: 'Headspace for Meditation, Mindfulness and Sleep',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 339974,
    downloadsLowerBound: 10000000,
  },
  workday: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.workday.workdroidapp&hl=en&gl=US',
    storeName: 'Workday',
    publisher: 'Workday, Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 264997,
    downloadsLowerBound: 10000000,
  },
  'spaces-by-wix': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.wix.android&hl=en&gl=US',
    storeName: 'Spaces: Follow Businesses',
    publisher: 'Wix.com, INC.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 94971,
    downloadsLowerBound: 10000000,
  },
  x: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.twitter.android&hl=en&gl=US',
    storeName: 'X',
    publisher: 'X Corp.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 24094868,
    downloadsLowerBound: 1000000000,
  },
  meetup: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.meetup&hl=en&gl=US',
    storeName: 'Meetup: Social Events & Groups',
    publisher: 'Meetup',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 234967,
    downloadsLowerBound: 10000000,
  },
  'wix-owner': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.wix.admin&hl=en&gl=US',
    storeName: 'Wix - Website Builder',
    publisher: 'Wix.com, INC.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 66985,
    downloadsLowerBound: 5000000,
  },
  'sncf-connect': {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.vsct.vsc.mobile.horaireetresa.android&hl=en&gl=US',
    storeName: 'SNCF Connect: Trains & routes',
    publisher: 'SNCF Connect & Tech',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 608544,
    downloadsLowerBound: 10000000,
  },
  'cash-app': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.squareup.cash&hl=en&gl=US',
    storeName: 'Cash App',
    publisher: 'Block, Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 4423188,
    downloadsLowerBound: 100000000,
  },
  prezzee: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.prezzee.prezzee&hl=en&gl=US',
    storeName: 'Prezzee eGift cards',
    publisher: 'Prezzee Pty. Limited',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 4976,
    downloadsLowerBound: 1000000,
  },
  hipcamp: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.hipcamp.pocketknife&hl=en&gl=US',
    storeName: 'Hipcamp: Camping, RVs & Cabins',
    publisher: 'Hipcamp, Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 16022,
    downloadsLowerBound: 1000000,
  },
  'down-dog': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.downdogapp&hl=en&gl=US',
    storeName: 'Yoga | Down Dog',
    publisher: 'Yoga Buddhi Co.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 377878,
    downloadsLowerBound: 5000000,
  },
  phantom: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=app.phantom&hl=en&gl=US',
    storeName: 'Phantom: Trading Wallet',
    publisher: 'Phantom Technologies, Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 152639,
    downloadsLowerBound: 10000000,
  },
  partiful: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.partiful.partiful&hl=en&gl=US',
    storeName: 'Partiful: Party Invite Maker',
    publisher: 'Partiful',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 23296,
    downloadsLowerBound: 500000,
  },
  'virgin-money': {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.virginmoney.uk.mobile.android&hl=en&gl=US',
    storeName: 'Virgin Money Mobile Banking',
    publisher: 'Nationwide Building Society T/A Virgin Money',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 33716,
    downloadsLowerBound: 1000000,
  },
  fastwork: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.fastwork.app&hl=en&gl=US',
    storeName: 'Fastwork - Hire Freelancers',
    publisher: 'Fastwork Engineer',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 9367,
    downloadsLowerBound: 1000000,
  },
  'incident-io': {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.incidentio.incidentio&hl=en&gl=US',
    storeName: 'incident.io',
    publisher: 'incident.io',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 38,
    downloadsLowerBound: 10000,
  },
  'business-insider': {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.freerange360.mpp.businessinsider&hl=en&gl=US',
    storeName: 'Business Insider: News & more',
    publisher: 'Business Insider, Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 38973,
    downloadsLowerBound: 1000000,
  },
  lucid: {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.lucidmotors.mobile.prod&hl=en&gl=US',
    storeName: 'Lucid Motors',
    publisher: 'Lucid USA, Inc.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 225,
    downloadsLowerBound: 10000,
  },
  mollie: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.mollie.android&hl=en&gl=US',
    storeName: 'Mollie',
    publisher: 'Mollie BV',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 1483,
    downloadsLowerBound: 100000,
  },
  goody: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.ongoody.goody&hl=en&gl=US',
    storeName: 'Goody – Easy Gifting',
    publisher: 'Goody Technologies',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 624,
    downloadsLowerBound: 100000,
  },
  betterment: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.betterment&hl=en&gl=US',
    storeName: 'Betterment Invest & Save Money',
    publisher: 'Betterment',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 19182,
    downloadsLowerBound: 1000000,
  },
  kijiji: {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.ebay.kijiji.ca&hl=en&gl=US',
    storeName: 'Kijiji: Buy and sell local',
    publisher: 'Kijiji Canada Ltd.',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 315929,
    downloadsLowerBound: 10000000,
  },
  'caribou-coffee': {
    sourceUrl: 'https://play.google.com/store/apps/details?id=com.caribou.caribouapp&hl=en&gl=US',
    storeName: 'Caribou Coffee®',
    publisher: 'Caribou Coffee',
    region: 'US',
    checkedAt: '2026-09-06',
    ratingCount: 39206,
    downloadsLowerBound: 500000,
  },
  'google-pay': {
    sourceUrl:
      'https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.paisa.user&hl=en&gl=IN',
    storeName: 'Google Pay: Secure UPI payment',
    publisher: 'Google LLC',
    region: 'IN',
    checkedAt: '2026-09-06',
    ratingCount: 11318897,
    downloadsLowerBound: 1000000000,
  },
};
